### ISSUE TITLE
Potential issue with Mac OSX version ???

### ISSUE THREAD

**Issue by Thomasjkeel** [Thomasjkeel/jsmetrics#76]

**Comment by jimpala** [comment]
Hi, please provide more context when opening an issue so that we can reproduce your error - this gives you a better chance of us diagnosing and fixing it.

You can refer to our contributing guidelines [here](https://github.com/Thomasjkeel/jsmetrics/blob/main/CONTRIBUTING.rst).

> If you are reporting a bug, please include:
>
> - Your operating system name and version.
> - Any details about your local setup that might be helpful in troubleshooting.
> - Detailed steps to reproduce the bug.
